In [14]:
import pandas as pd
import json
df=pd.read_csv('/content/restaurants_small.csv')
df.head()

,id,name,location,items,lat_long,full_details
0,11116,Udupi Thaja Thindi,BTM,"{""2 Idli with 1 Vada"": ""60.00 "", ""Masala Dosa""...","12.9152311463,77.6001443714","{""name"": ""Udupi Thaja Thindi"", ""offers"": [], ""..."
1,9851,Momo Hut,Koramangala 5th Block,"{""Steamed Veg Momos"": ""90.00 "", ""Steamed Chick...","12.9341887415,77.6157491282","{""name"": ""Momo Hut"", ""offers"": [], ""cuisines"":..."
2,8380,Chandrika Tiffins,Whitefield,"{""Aloo Paratha"": ""35.00 "", ""Gobi Paratha"": ""40...","13.0157964869,77.7620874345","{""name"": ""Chandrika Tiffins"", ""offers"": [], ""c..."
3,8462,Shuchi Ruchi,Malleshwaram,"{""Gobi Manchurian"": ""90.00 "", ""Paneer Manchuri...","13.0011596277,77.5723362342","{""name"": ""Shuchi Ruchi"", ""offers"": [], ""cuisin..."
4,8466,Smiley's Kitchen,Koramangala 1st Block,"{""Egg Bhurji"": ""60.00 "", ""Aloo Paratha"": ""40.0...","12.9295714466,77.6324777305","{""name"": ""Smiley's Kitchen"", ""offers"": [], ""cu..."

In [15]:
# df1=pd.DataFrame(json.dumps(df.iloc[0]['items']))
df1 = pd.DataFrame.from_dict(json.loads(df.iloc[0]['items']), orient="index")
df1=df1.reset_index()
df1['Resturant_id']=df.iloc[0]['id']
# "{x} is even" if x %2==0 else f"{x} is odd
df1['item_details']=df1.apply(lambda x: x['index'].split('[')[1][:-1] if len(x['index'].split('[')) > 1 else "", axis=1)
df1['index']=df1.apply(lambda x: x['index'].split('[')[0] if len(x['index'].split('[')) > 1 else x['index'], axis=1)
# a=json.loads(df.iloc[0]['full_details'])
# if 'currency' in a:
#   df1['Currency']=a['currency']
for i in range(1,df.shape[0]):
  df2 = pd.DataFrame.from_dict(json.loads(df.iloc[i]['items']), orient="index")
  df2=df2.reset_index()
  df2['Resturant_id']=df.iloc[i]['id']
  df2['item_details']=df2.apply(lambda x: x['index'].split('[')[1][:-1] if len(x['index'].split('[')) > 1 else "", axis=1)
  df2['index']=df2.apply(lambda x: x['index'].split('[')[0] if len(x['index'].split('[')) > 1 else x['index'], axis=1)
  # try:
  #   a=json.loads(df.iloc[i]['full_details'])
  #   if 'currency' in a:
  #     df2['Currency']=a['currency']
  # except:
  #   pass
  df1=pd.concat([df1, df2])
  # df1.append(df2,ignore_index = True)

In [16]:
df1.tail()

                                    index         0  Resturant_id item_details
53   Share-E-Biryani (Non-Veg) (Serves 2)   609.52          11042
54       Jashn-E-Biryani (Veg) (Serves 4)  1000.00          11042
55   Jashn-E-Biryani (Non Veg) (Serves 4)  1142.86          11042
56      Mehfil-E-Biryani (Veg) (Serves 8)  2285.71          11042
57  Mehfil-E-Biryani (Non Veg) (Serves 8)  2619.05          11042

In [17]:
df1=df1.reset_index()
df1=df1.drop(['level_0'], axis=1)
df1.head()

                    index       0  Resturant_id item_details
0      2 Idli with 1 Vada  60.00          11116
1             Masala Dosa  60.00          11116
2         Gobi Manchurian  95.00          11116
3             Tomato Soup  75.00          11116
4  Cream of Mushroom Soup  80.00          11116

In [18]:
df1['index'] = df1['index'].str.strip()
df1.head()

                    index       0  Resturant_id item_details
0      2 Idli with 1 Vada  60.00          11116
1             Masala Dosa  60.00          11116
2         Gobi Manchurian  95.00          11116
3             Tomato Soup  75.00          11116
4  Cream of Mushroom Soup  80.00          11116

In [22]:
df3=(df1
 .groupby(['index'])['Resturant_id'].count()
)
df3=df3.reset_index()
df3=df3.sort_values(by=['Resturant_id'],ascending=False)
df3=df3[df3['Resturant_id']>5]
df3=df3.reset_index()

In [23]:
df3.head()

   level_0                 index  Resturant_id
0    22732        Veg Fried Rice           213
1    11498            Jeera Rice           194
2     4498    Chicken Fried Rice           190
3     8489        Egg Fried Rice           180
4    16469  Paneer Butter Masala           179

In [24]:
df3.to_csv('Menu_items.csv')

In [ ]:
df1.to_csv('Menu_details.csv')

In [ ]:
    # ID=models.IntegerField(primary_key=True)
    # Resturant_Name=models.CharField(max_length=255)
    # Location=models.CharField(max_length=255,default=None, blank=True, null=True)
    # Latitude=models.CharField(max_length=255,default=None, blank=True, null=True)
    # Longitude=models.CharField(max_length=255,default=None, blank=True, null=True)
    # Rating= models.FloatField(default=None, blank=True, null=True)
    # No_of_votes= models.IntegerField(default=None, blank=True, null=True)
    # True_rating= models.FloatField(default=None, blank=True, null=True)

In [ ]:
import pandas as pd
import json
df=pd.read_csv('/content/restaurants_small.csv')
df['Latitude']= df.apply(lambda x: x['lat_long'].split(',')[0] if len(x['lat_long'].split(',')) > 1 else "", axis=1)
df['Longitude']= df.apply(lambda x: x['lat_long'].split(',')[1] if len(x['lat_long'].split(',')) > 1 else "", axis=1)
df['Rating']=0.0
df['No_of_votes']=0
for i in range(0,df.shape[0]):
  try:
    a=json.loads(df.iloc[i]['full_details'])
    if 'user_rating' in a:
      df.iat[i,8]=a['user_rating']['aggregate_rating']
      df.iat[i,9]=a['user_rating']['votes']
  except:
    pass
df['True_rating']= 0.45*df['Rating'].astype(float) + 0.55*df['No_of_votes'].astype(float)
df['True_rating'] = (df['True_rating'] - df['True_rating'].min()) / (df['True_rating'].max() - df['True_rating'].min())
df.head()

,id,name,location,items,lat_long,full_details,Latitude,Longitude,Rating,No_of_votes,True_rating
0,11116,Udupi Thaja Thindi,BTM,"{""2 Idli with 1 Vada"": ""60.00 "", ""Masala Dosa""...","12.9152311463,77.6001443714","{""name"": ""Udupi Thaja Thindi"", ""offers"": [], ""...",12.9152311463,77.6001443714,2.7,38,0.010579
1,9851,Momo Hut,Koramangala 5th Block,"{""Steamed Veg Momos"": ""90.00 "", ""Steamed Chick...","12.9341887415,77.6157491282","{""name"": ""Momo Hut"", ""offers"": [], ""cuisines"":...",12.9341887415,77.6157491282,4.0,657,0.173725
2,8380,Chandrika Tiffins,Whitefield,"{""Aloo Paratha"": ""35.00 "", ""Gobi Paratha"": ""40...","13.0157964869,77.7620874345","{""name"": ""Chandrika Tiffins"", ""offers"": [], ""c...",13.0157964869,77.7620874345,3.8,43,0.012132
3,8462,Shuchi Ruchi,Malleshwaram,"{""Gobi Manchurian"": ""90.00 "", ""Paneer Manchuri...","13.0011596277,77.5723362342","{""name"": ""Shuchi Ruchi"", ""offers"": [], ""cuisin...",13.0011596277,77.5723362342,3.9,286,0.076089
4,8466,Smiley's Kitchen,Koramangala 1st Block,"{""Egg Bhurji"": ""60.00 "", ""Aloo Paratha"": ""40.0...","12.9295714466,77.6324777305","{""name"": ""Smiley's Kitchen"", ""offers"": [], ""cu...",12.9295714466,77.6324777305,0,1,0.000263

In [ ]:
df=df.drop(['items','lat_long','full_details'],axis=1)
df.head(20)

,id,name,location,Latitude,Longitude,Rating,No_of_votes,True_rating
0,11116,Udupi Thaja Thindi,BTM,12.9152311463,77.6001443714,2.7,38,0.010579
1,9851,Momo Hut,Koramangala 5th Block,12.9341887415,77.6157491282,4.0,657,0.173725
2,8380,Chandrika Tiffins,Whitefield,13.0157964869,77.7620874345,3.8,43,0.012132
3,8462,Shuchi Ruchi,Malleshwaram,13.0011596277,77.5723362342,3.9,286,0.076089
4,8466,Smiley's Kitchen,Koramangala 1st Block,12.9295714466,77.6324777305,0,1,0.000263
5,8476,Lazeez Corner,HSR,12.8958148924,77.6579617336,0,1,0.000263
6,10508,Urban Solace - Café for the Soul,Ulsoor,12.9849553700,77.6183468476,3.8,435,0.115271
7,9903,Azura Restaurant,Bellandur,12.9267025600,77.6785070300,2.8,88,0.023757
8,8042,Pure Andhra Style Reddy's Restaurant,HSR,12.9122559938,77.6342788339,3.7,135,0.036316
9,9861,YumYumDilli,Hennur,13.0333627781,77.6350469515,2.9,101,0.027198
10,9862,Shan-e-Punjabi Express,Whitefield,12.9786320000,77.7414527000,3.0,40,0.011170
11,11394,Delhi Delight Food Cafe,Kaggadasapura,12.9680570000,77.6701760000,3.7,24,0.007111
12,9867,Snack Knack,BTM,12.9106213441,77.6099488512,2.9,33,0.009307
13,10973,Spicy House,Marathahalli,12.9530975182,77.6982324198,2.8,68,0.018494
14,9877,Pappu Da Dhaba,Jayanagar,12.9164879938,77.5926492736,3.6,52,0.014457
15,9972,Saha Chowmein,Sahakara Nagar,13.0629097614,77.5868500024,3.8,147,0.039495
16,9560,Wok Chow,Sanjay Nagar,13.0478610000,77.5741230000,3.6,112,0.030243
17,10150,Oz Pies,Bellandur,12.9221930000,77.6763000000,3.7,32,0.009216
18,11302,Hyderabad Cuisine,"Varthur Main Road, Whitefield",12.9567754000,77.7362292000,2.7,65,0.017683
19,9982,Say Cheeze,Kanakapura Road,12.8799783467,77.5459979475,2.8,12,0.003760

In [ ]:
df.to_csv('resturant_details.csv')